### ISSUE TITLE
Cron job task fails to remove cron job if setting changed from present to absent

### ISSUE THREAD

**Issue by kfiresmith** [kfiresmith/ansible-role-scheduled-reboot#1]
The `when:` logic on the cron job task is all wrong.

Corrected task is:
```yaml
- name: Manage cron job presence and settings
  ansible.builtin.cron:
    name: scheduled-reboot
    cron_file: scheduled-reboot
    user: root
    job: 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin /usr/local/bin/scheduled-reboot'
    state: "{{ scheduled_reboot_cronjob_state }}"
    minute: "{{ reboot_schedule.split(' ')[0] }}"
    hour: "{{ reboot_schedule.split(' ')[1] }}"
    day: "{{ reboot_schedule.split(' ')[2] }}"
    month: "{{ reboot_schedule.split(' ')[3] }}"
    weekday: "{{ reboot_schedule.split(' ')[4] }}"
  when: reboot_schedule is defined and scheduled_reboot_cronjob_state is defined
```
